// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  List all projects from the SQLite index with optional filtering (BROW-02, MGMT-04).
	 * 
	 *  This is a pure SQLite query — it never re-parses binary files (see RESEARCH.md pitfall 1).
	 */
	listProjects: (filter: ProjectFilter) => typedError<ProjectSummary[], AppError>(__TAURI_INVOKE("list_projects", { filter })),
	/**
	 *  Return full project detail by reading project.work + bank files via ot-parser (BROW-05).
	 * 
	 *  Threat model T-02-04: project_id is an opaque UUID — card_path is resolved from DB,
	 *  never from a frontend-supplied path.
	 * 
	 *  NOTE: The ot-parser `project.work` / `bank.work` parsers are not yet implemented
	 *  (Phase 1 OT binary spec work pending). This command returns a stub ProjectDetail
	 *  built from what is available in the SQLite index until the parser is ready.
	 *  Assumption guard A2: raw_tempo / TEMPO_SCALE_FACTOR gives the display BPM.
	 */
	getProjectDetail: (projectId: string) => typedError<ProjectDetail, AppError>(__TAURI_INVOKE("get_project_detail", { projectId })),
	/**
	 *  Return the 16-bank summary grid for a project (BROW-03).
	 * 
	 *  Assumption guard (Open Question 4): `is_bank_populated` is isolated so the logic
	 *  can be adjusted once Phase 1 binary parser fixtures are available.
	 * 
	 *  NOTE: Until the ot-parser bank file parser exists, this returns stub data
	 *  derived from the bank_count in the SQLite index.
	 */
	getProjectBanks: (projectId: string) => typedError<BankSummary[], AppError>(__TAURI_INVOKE("get_project_banks", { projectId })),
	/**
	 *  Walk the SETS directory on the mounted OT volume, parse each project.work file,
	 *  and upsert into the SQLite projects table (called on volume mount).
	 * 
	 *  Threat model T-02-02: volume_path comes from AppState (set by Phase 1 volume
	 *  detection), not from the frontend.
	 * 
	 *  Assumption guard (Open Question 3): Tries project.work first; falls back to
	 *  project.strd if .work does not exist.
	 * 
	 *  Assumption guard A2: tempo stored as integer × TEMPO_SCALE_FACTOR.
	 */
	indexOtProjects: () => typedError<number, AppError>(__TAURI_INVOKE("index_ot_projects")),
	/**
	 *  Return all 128 Flex and 128 Static sample slots for a project (BROW-04).
	 * 
	 *  Reads project.work via ot-parser. Until the Phase 1 parser for project.work
	 *  is implemented, returns stub empty slot arrays.
	 * 
	 *  Assumption guard A3: All path normalization goes through `normalize_ot_path()`.
	 */
	getProjectSamples: (projectId: string) => typedError<SampleSlotResponse, AppError>(__TAURI_INVOKE("get_project_samples", { projectId })),
	// Get the current device connection status.
	getDeviceStatus: () => typedError<DeviceStatus, AppError>(__TAURI_INVOKE("get_device_status")),
	/**
	 *  Confirm the detected OT volume for use.
	 *  Sets the device as confirmed and returns success.
	 */
	confirmDevice: (mountPoint: string) => typedError<null, AppError>(__TAURI_INVOKE("confirm_device", { mountPoint })),
	// Dismiss/disconnect the device.
	dismissDevice: () => typedError<null, AppError>(__TAURI_INVOKE("dismiss_device")),
	/**
	 *  Trigger the health check for a project.
	 * 
	 *  Returns `Ok(())` immediately after spawning the background task — never blocks
	 *  on file I/O (RESEARCH.md Pitfall 2: "Health Check Blocking the UI Thread").
	 * 
	 *  Results are emitted as a "health-complete" event carrying a `HealthCheckComplete`
	 *  payload when the background scan finishes. The frontend listens for this event
	 *  and stores results in react-query cache.
	 * 
	 *  Threat model T-02-06: `project_id` is resolved to `card_path` via SQLite — the
	 *  frontend never supplies a raw file path.
	 */
	runHealthCheck: (projectId: string) => typedError<null, AppError>(__TAURI_INVOKE("run_health_check", { projectId })),
	/**
	 *  Back up an OT project to ~/takoyaki/backups/PROJECT_NAME/TIMESTAMP_label/ (SAFE-01, SAFE-02).
	 * 
	 *  Streams per-file progress via Channel. Checks AtomicBool cancel_flag per file (SAFE-06).
	 *  Computes SHA-256 checksums to verify copy integrity (SAFE-02).
	 *  Records backup in SQLite with status='in-progress'; marks complete on success (SAFE-05, D-12).
	 * 
	 *  T-03-01: Destination computed in Rust only — frontend supplies project_id + label, not path.
	 *  T-03-04: DB lock released before file I/O loop to avoid deadlock (Pitfall 4).
	 */
	backupProject: (projectId: string, label: string, onEvent: Channel<BackupEvent>) => typedError<null, AppError>(__TAURI_INVOKE("backup_project", { projectId, label, onEvent })),
	/**
	 *  Restore an OT project from a backup snapshot (SAFE-06, SAFE-04, D-11).
	 * 
	 *  Creates a pre-restore snapshot of the current project state before overwriting (D-11).
	 *  Writes all files atomically via atomic_write_batch (SAFE-04: FAT32 rename atomicity).
	 * 
	 *  T-03-02: backup_id resolved to dest_path via DB lookup — frontend never supplies raw paths.
	 *  T-03-04: DB lock released before file I/O.
	 */
	restoreSnapshot: (backupId: string, onEvent: Channel<BackupEvent>) => typedError<null, AppError>(__TAURI_INVOKE("restore_snapshot", { backupId, onEvent })),
	/**
	 *  Compute a dry-run manifest showing what a backup or restore would change (SAFE-07).
	 * 
	 *  This function MUST NOT modify any files — it only reads and computes hashes.
	 * 
	 *  For "backup": all project files are "Added" (new backup destination).
	 *  For "restore": compares backup files against current card state.
	 */
	computeDryRun: (projectId: string, operation: string, backupId: string | null) => typedError<FileChangeManifest, AppError>(__TAURI_INVOKE("compute_dry_run", { projectId, operation, backupId })),
	// List backups for a project (or all projects if project_id is None) (SAFE-05).
	listBackups: (projectId: string | null) => typedError<BackupSummary[], AppError>(__TAURI_INVOKE("list_backups", { projectId })),
	// Set the cancellation flag — backup_project will stop at the next file boundary.
	cancelBackup: () => typedError<null, AppError>(__TAURI_INVOKE("cancel_backup")),
	/**
	 *  Compute a dry-run manifest showing what a management operation would change (SAFE-07).
	 * 
	 *  Returns a `FileChangeManifest` without modifying any files.
	 *  For bank-copy, uses SHA-256 conflict detection (T-04-06).
	 * 
	 *  T-03-04: DB lock released before all file I/O.
	 *  T-04-07: new_name validated via validate_ot_name before use.
	 */
	computeManagementDryRun: (projectId: string, operation: string, targetProjectId: string | null, bankIndex: number | null, newName: string | null) => typedError<FileChangeManifest, AppError>(__TAURI_INVOKE("compute_management_dry_run", { projectId, operation, targetProjectId, bankIndex, newName })),
	/**
	 *  Duplicate an OT project with pre-operation snapshot (SAFE-03).
	 * 
	 *  T-04-07: new_name validated via validate_ot_name.
	 *  T-03-04: DB lock released before file I/O.
	 */
	duplicateProject: (projectId: string, newName: string, onEvent: Channel<ManagementEvent>) => typedError<null, AppError>(__TAURI_INVOKE("duplicate_project", { projectId, newName, onEvent })),
	/**
	 *  Rename an OT project with pre-operation snapshot (SAFE-03).
	 * 
	 *  Updates the DB `card_path` after successful rename.
	 *  No channel needed — rename is fast and synchronous.
	 * 
	 *  T-04-07: new_name validated via validate_ot_name.
	 *  T-03-04: DB lock released before file I/O, re-acquired for DB update.
	 */
	renameProject: (projectId: string, newName: string) => typedError<null, AppError>(__TAURI_INVOKE("rename_project", { projectId, newName })),
	/**
	 *  Export an OT project to a self-contained zip archive.
	 * 
	 *  Export is read-only — no snapshot needed (nothing on the card is modified).
	 *  Zip is written to ~/takoyaki/exports/{project_name}_{timestamp}.zip (D-06).
	 * 
	 *  T-03-04: DB lock released before file I/O.
	 */
	exportProject: (projectId: string, onEvent: Channel<ManagementEvent>) => typedError<null, AppError>(__TAURI_INVOKE("export_project", { projectId, onEvent })),
	/**
	 *  Copy a bank from source project to target project, with pre-operation snapshot (SAFE-03).
	 * 
	 *  Streams progress via Channel. Pre-snapshots ALL files in target project (Pitfall 3).
	 * 
	 *  T-04-09: conflict_resolutions values validated in copy_bank() business logic.
	 *  T-03-04: DB lock released before file I/O.
	 */
	copyBank: (sourceProjectId: string, sourceBankIndex: number, targetProjectId: string, targetBankIndex: number, conflictResolutions: { [key in string]: string }, onEvent: Channel<ManagementEvent>) => typedError<null, AppError>(__TAURI_INVOKE("copy_bank", { sourceProjectId, sourceBankIndex, targetProjectId, targetBankIndex, conflictResolutions, onEvent })),
};

/* Types */
export type AppError = ({ Io: string }) & { Cancelled?: never; Database?: never; Device?: never; Lock?: never; Parse?: never } | ({ Parse: string }) & { Cancelled?: never; Database?: never; Device?: never; Io?: never; Lock?: never } | ({ Database: string }) & { Cancelled?: never; Device?: never; Io?: never; Lock?: never; Parse?: never } | ({ Lock: string }) & { Cancelled?: never; Database?: never; Device?: never; Io?: never; Parse?: never } | ({ Device: string }) & { Cancelled?: never; Database?: never; Io?: never; Lock?: never; Parse?: never } | "InvalidPath" | ({ Cancelled: string }) & { Database?: never; Device?: never; Io?: never; Lock?: never; Parse?: never };

// Events emitted to the frontend during backup and restore operations.
export type BackupEvent = { event: "started"; data: {
	total_files: number,
	destination: string,
} } | { event: "progress"; data: {
	files_copied: number,
	total_files: number,
	current_file: string,
} } | { event: "complete"; data: {
	files_copied: number,
	total_bytes: number,
	destination: string,
	checksum_ok: boolean,
} } | { event: "failed"; data: {
	reason: string,
} };

// A backup summary row as returned by list queries (SAFE-05).
export type BackupSummary = {
	id: string,
	project_id: string,
	project_name: string,
	dest_path: string,
	created_at: string,
	operation: string,
	file_count: number,
	total_bytes: number,
	checksum_ok: boolean,
	status: string,
};

// One bank (0-indexed) within a project.
export type BankDetail = {
	bank_index: number,
	populated: boolean,
	bank_name: string | null,
	parts: PartDetail[],
};

// Lightweight bank summary for the 4×4 grid view (BROW-03).
export type BankSummary = {
	bank_index: number,
	populated: boolean,
	pattern_count: number,
};

// Change type classification for dry-run manifests (SAFE-07).
export type ChangeType = "Added" | "Modified" | "Removed" | "Unchanged" | 
// Hash-mismatch conflict detected during bank copy (Phase 4 D-08).
"Conflict";

// Conflict detail for bank copy operations (D-08 resolution UI, Plan 04-07).
export type ConflictDetail = {
	filename: string,
	source_hash: string,
	target_hash: string,
};

export type DeviceStatus = {
	connected: boolean,
	mountPoint: string | null,
	confirmed: boolean,
};

// A single file entry in a dry-run manifest.
export type FileChangeEntry = {
	// Relative path from project root.
	path: string,
	change_type: ChangeType,
	size_bytes: number,
};

// Full dry-run manifest returned by compute_dry_run (SAFE-07).
export type FileChangeManifest = {
	entries: FileChangeEntry[],
	total_added: number,
	total_modified: number,
	total_removed: number,
	total_unchanged: number,
	total_bytes: number,
	destination_path: string,
	operation_label: string,
	project_name: string,
	// Populated for bank-copy operations only — empty for backup/restore/duplicate/rename/export.
	conflict_details: ConflictDetail[],
};

/**
 *  Events emitted to the frontend during management operations.
 * 
 *  Mirrors `BackupEvent` shape (Plan 03-02 pattern) for consistent frontend handling.
 */
export type ManagementEvent = { event: "started"; data: {
	total_files: number,
	destination: string,
} } | { event: "progress"; data: {
	files_processed: number,
	total_files: number,
	current_file: string,
} } | { event: "complete"; data: {
	files_processed: number,
	total_bytes: number,
	destination: string,
} } | { event: "failed"; data: {
	reason: string,
} };

// One part (0-indexed, 4 per bank) within a bank.
export type PartDetail = {
	part_index: number,
	part_name: string | null,
	tracks: TrackDetail[],
};

// Full project detail (BROW-05).
export type ProjectDetail = {
	project_name: string,
	// Actual BPM value after dividing raw value by TEMPO_SCALE_FACTOR.
	tempo_bpm: number,
	bank_count: number,
	last_modified: string | null,
	banks: BankDetail[],
};

/**
 *  Filter parameters for project list queries (MGMT-04).
 * 
 *  All fields optional — an empty filter returns all projects.
 */
export type ProjectFilter = {
	name: string | null,
	bpm_min: number | null,
	bpm_max: number | null,
	// ISO 8601 date string, e.g. "2026-01-01"
	modified_since: string | null,
};

// A project row as returned by the list query (BROW-02).
export type ProjectSummary = {
	id: string,
	set_name: string,
	project_name: string,
	card_path: string,
	// Actual BPM value (e.g. 120.0), NOT the raw stored integer.
	tempo_bpm: number | null,
	// Number of banks used out of 16.
	bank_count: number | null,
	// ISO date string.
	last_modified: string | null,
};

// One sample slot (0-indexed, 0..=127 for Flex and Static each).
export type SampleSlot = {
	slot_index: number,
	occupied: boolean,
	// Just the filename portion (not full path) for table display.
	filename: string | null,
	// The raw path from the OT binary, normalized via `normalize_ot_path()`.
	full_path: string | null,
	sample_rate: number | null,
	// "ok", "missing", "warning", or "unknown" — populated by health check.
	status: string,
};

// Response containing both Flex and Static sample slot arrays (BROW-04).
export type SampleSlotResponse = {
	flex: SampleSlot[],
	static_slots: SampleSlot[],
};

// One track (0-indexed, 8 per part) within a part.
export type TrackDetail = {
	track_index: number,
	// "Flex", "Static", "Thru", "Neighbor", or "Pickup"
	machine_type: string,
	sample_slot_index: number | null,
	sample_filename: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

